"use client"

import { CreditCard, ReceiptText, Plus, Check, Package, Banknote, ShoppingBag, ArrowUpRight, Landmark, Plane, Search, Bell } from "lucide-react"
import { IdentidadeBanco } from "@/components/banco-perfil"
import { EntradasESaidas } from "@/components/entradas-saidas"
import { formatarMoeda } from "@/lib/dinheiro"
import inicio from "@/app/(app)/painel/inicio.module.css"
import carteira from "@/components/carteira-cartoes.module.css"
import balcao from "@/app/(app)/loja/balcao.module.css"
import estilos from "./demonstracao-sistema.module.css"

export type TelaDemonstracao = "inicio" | "extrato" | "dividas" | "cartoes" | "analise" | "milhas" | "balcao" | "estoque" | "fiado" | "caixa"
export const TELAS_PESSOAIS = [
  { chave: "inicio", nome: "Início", chamada: "O seu mês, em um olhar.", apoio: "Saldo, compras e próximos passos juntos." },
  { chave: "cartoes", nome: "Cartões", chamada: "A próxima fatura já está no radar.", apoio: "Alterne cartões e acompanhe suas parcelas." },
  { chave: "analise", nome: "Análise", chamada: "Entenda para onde foi.", apoio: "Compare os gastos e encontre espaço no orçamento." },
  { chave: "milhas", nome: "Pontos e milhas", chamada: "Suas compras também rendem.", apoio: "Configure a regra e acompanhe a previsão de pontos." },
] as const
export const TELAS_MEI = [
  { chave: "balcao", nome: "Balcão", chamada: "Da venda ao caixa. Sem perder o ritmo.", apoio: "Valor, pagamento e registro no mesmo lugar." },
  { chave: "estoque", nome: "Estoque", chamada: "Saiba o que tem. E o que repor.", apoio: "Produtos, custo e margem na sua prateleira." },
  { chave: "fiado", nome: "Fiado", chamada: "Cada recebimento no radar.", apoio: "Veja quem deve e acompanhe as cobranças." },
  { chave: "caixa", nome: "Caixa", chamada: "Feche o dia com clareza.", apoio: "Confira vendas e valores antes de encerrar." },
] as const
const COMPRAS = [{ nome: "Supermercado", valor: 28645 }, { nome: "Combustível", valor: 18000 }, { nome: "Farmácia", valor: 8490 }, { nome: "Delivery", valor: 6290 }, { nome: "Assinaturas", valor: 5590 }, { nome: "Transporte", valor: 2870 }]

/** HTML da vitrine, com dados fictícios e estilos atuais do produto.
 * Sem sessão, chamadas de API ou gravação: visitante nunca opera uma conta real.
 */
export function PreviaSistema({ tela }: { tela: TelaDemonstracao }) {
  if (tela === "analise") return <div className={estilos.analise}><EntradasESaidas mes="Outubro de 2026 · exemplo" receitasCentavos={860000} despesasCentavos={69885} grupos={[
    { grupo: "ALIMENTACAO", nome: "Alimentação", totalCentavos: 34935, percentualDaReceita: 406 },
    { grupo: "TRANSPORTE", nome: "Transporte", totalCentavos: 20870, percentualDaReceita: 243 },
    { grupo: "SAUDE", nome: "Saúde", totalCentavos: 8490, percentualDaReceita: 99 },
    { grupo: "LAZER", nome: "Lazer", totalCentavos: 5590, percentualDaReceita: 65 },
  ]} custoFixoCentavos={518800} custoVariavelCentavos={0} patrimonio={{ liquidoCentavos: 3848715, temCentavos: 8270965, deveCentavos: 4422250 }}><p>Exemplo de patrimônio: ativos menos dívidas.</p></EntradasESaidas></div>
  if (tela === "extrato") return <Bloco titulo="Movimentos de outubro"><Linhas linhas={[{ nome: "Salário · exemplo", nota: "Entrada · 01 de outubro", valor: 860000 }, ...COMPRAS.map((compra) => ({ ...compra, valor: -compra.valor, nota: "Saída · 01 de outubro" }))]} /></Bloco>
  if (tela === "dividas") return <><Metrica nome="Você deve · exemplo" valor="R$ 31.750,00" /><Bloco titulo="Maior juro primeiro"><Linhas linhas={[{ nome: "Cheque especial", nota: "7,80% ao mês", valor: 185000 }, { nome: "Empréstimo pessoal", nota: "2,89% ao mês · 9 de 24 parcelas", valor: 840000 }, { nome: "Financiamento do carro", nota: "1,58% ao mês · 19 de 48 parcelas", valor: 2150000 }]} /></Bloco><Bloco titulo="Antecipe sua quitação"><p className={estilos.nota}>Compare prazo e juros ao aumentar o pagamento mensal.</p><div className={estilos.confirmacao}>+ R$ 250,00 por mês · exemplo de valor extra</div></Bloco></>
  if (tela === "cartoes") return <><div className={estilos.duasColunas}>{[
    { nome: "Platinum", instituicao: "Banco do Brasil", final: "8842", bandeira: "Visa", fatura: 312460, cor: "#756900" },
    { nome: "Gold", instituicao: "Nubank", final: "3317", bandeira: "Mastercard", fatura: 132290, cor: "#54208b" },
  ].map((cartao) => <article className={carteira.cartao} key={cartao.nome} style={{ "--cor-banco": cartao.cor, position: "relative", top: 0, transform: "none" } as React.CSSProperties}><span className={carteira.topo}><IdentidadeBanco instituicao={cartao.instituicao} nome={cartao.nome} className={carteira.logo} /><span className={carteira.banco}><strong>{cartao.instituicao}</strong><small>{cartao.nome}</small></span><span className={carteira.bandeira}>{cartao.bandeira}</span></span><span className={carteira.meio}><i className={carteira.chip} /><span className={carteira.final}>•••• {cartao.final}</span></span><span className={carteira.base}><span><small>Fatura atual</small><strong>{formatarMoeda(cartao.fatura)}</strong></span><span className={carteira.vencimento}><small>Vence dia 6</small></span></span></article>)}</div><Bloco titulo="Próximas parcelas"><Linhas linhas={[{ nome: "Novembro", nota: "Parcelas já compradas", valor: 88000 }, { nome: "Dezembro", nota: "Parcelas já compradas", valor: 88000 }, { nome: "Janeiro", nota: "Parcelas já compradas", valor: 88000 }]} /></Bloco></>
  if (tela === "milhas") return <><div className={estilos.programas}>{[{ nome: "Livelo", logo: "livelo" }, { nome: "Smiles", logo: "smiles" }, { nome: "LATAM Pass", logo: "latam-pass" }, { nome: "Azul", logo: "azul" }].map((programa) => <div key={programa.nome}><img src={`/milhas/${programa.logo}.svg`} alt="" /><b>{programa.nome}</b></div>)}</div><Bloco titulo="Acúmulo do Platinum"><div className={estilos.duasColunas}><Metrica nome="Saldo informado · Livelo" valor="32.500 pontos" /><Metrica nome="Previsão do mês" valor="1.692 pontos" /></div><p className={estilos.nota}>Exemplo: R$ 4.000 em compras · 2,2 pontos por dólar · câmbio R$ 5,20.</p></Bloco><Bloco titulo="Parcelas futuras"><Linhas linhas={[{ nome: "Novembro", nota: "R$ 880 em parcelas", texto: "372 pontos" }, { nome: "Dezembro", nota: "R$ 880 em parcelas", texto: "372 pontos" }, { nome: "Janeiro", nota: "R$ 880 em parcelas", texto: "372 pontos" }]} /></Bloco></>
  if (tela === "balcao") return <div className={estilos.duasColunas}><section className={`${balcao.bloco} ${estilos.balcao}`}><span className={estilos.nota}>Nova venda · exemplo</span><strong className={estilos.valorVenda}>R$ 45,00</strong><div className={estilos.teclado}>{["1", "2", "3", "4", "5", "6", "7", "8", "9", ",", "0", "⌫"].map((tecla) => <span key={tecla}>{tecla}</span>)}</div><div className={estilos.pagamentos}><span>Dinheiro</span><span>Pix</span><span>Cartão</span></div><span className={estilos.confirmacao}><Check size={16} /> Registrar venda</span></section><Bloco titulo="O dia no balcão"><Metrica nome="Vendido hoje · 18 vendas" valor="R$ 1.240,00" /><Linhas linhas={[{ nome: "Venda 018", nota: "Pix · 14:32", valor: 4500 }, { nome: "Venda 017", nota: "Dinheiro · 14:18", valor: 2800 }, { nome: "Venda 016", nota: "Cartão · 14:05", valor: 7600 }]} /></Bloco></div>
  if (tela === "estoque") return <><div className={estilos.duasColunas}><Metrica nome="Produtos na prateleira" valor="24" /><Metrica nome="Precisam de reposição" valor="3" /></div><Bloco titulo="Sua prateleira"><Linhas linhas={[{ nome: "Café 500 g", nota: "12 unidades · margem 25%", valor: 1800 }, { nome: "Arroz 5 kg", nota: "4 unidades · estoque baixo", valor: 2800 }, { nome: "Leite 1 L", nota: "32 unidades · margem 20%", valor: 600 }, { nome: "Sabonete", nota: "18 unidades · margem 30%", valor: 500 }]} /><div className={estilos.alerta}><Package size={18} /><span>Arroz: estoque baixo. Hora de repor.</span></div></Bloco></>
  if (tela === "fiado") return <><div className={estilos.duasColunas}><Metrica nome="A receber" valor="R$ 360,00" /><Metrica nome="Clientes com saldo" valor="3" /></div><Bloco titulo="Quem deve"><Linhas linhas={[{ nome: "Ana · exemplo", nota: "Vence hoje", valor: 12000 }, { nome: "João · exemplo", nota: "Vence em 3 dias", valor: 8500 }, { nome: "Maria · exemplo", nota: "Vence em 7 dias", valor: 15500 }]} /></Bloco><Bloco titulo="Cobrança organizada"><p className={estilos.nota}>Confira o saldo, registre o recebimento e prepare a mensagem de cobrança.</p></Bloco></>
  if (tela === "caixa") return <><div className={estilos.duasColunas}><Metrica nome="Vendido hoje" valor="R$ 1.240,00" /><Metrica nome="Dinheiro esperado na gaveta" valor="R$ 560,00" /></div><Bloco titulo="Resumo dos recebimentos"><Linhas linhas={[{ nome: "Dinheiro", valor: 46000 }, { nome: "Pix", valor: 48000 }, { nome: "Cartão", valor: 30000 }, { nome: "Fundo de abertura", valor: 10000 }]} /></Bloco><Bloco titulo="Conferir antes de fechar"><p className={estilos.nota}>Conte o dinheiro da gaveta. O fechamento compara o valor informado com o esperado.</p><div className={estilos.confirmacao}><Check size={16} /> Fechamento conferido · exemplo</div></Bloco></>
  return <><div className={estilos.duasColunas}><Metrica nome="Saldo disponível · exemplo" valor="R$ 17.699,65" /><Metrica nome="Sobrou no mês" valor="R$ 7.901,15" /></div><div className={estilos.duasColunas}><Bloco titulo="Compras recentes"><Linhas linhas={COMPRAS.map((compra) => ({ ...compra, nota: "01 de outubro · exemplo" }))} /></Bloco><Bloco titulo="Conferir"><div className={estilos.captura}><ReceiptText size={24} /><strong>Comprimidos</strong><small>30 de setembro · anotado</small><b>R$ 10,00</b><span className={estilos.nota}>Escolha a categoria antes de confirmar.</span><div className={estilos.confirmacao}><Check size={16} /> Confirmar · demonstração</div></div><div className={estilos.anotar}><Plus size={18} /> Anotar ou ditar uma compra</div></Bloco></div><Bloco titulo="Para onde foi"><div className={estilos.distribuicao}>{COMPRAS.map((compra, i) => <div key={compra.nome}><span>{compra.nome}<b>{formatarMoeda(compra.valor)}</b></span><i><span style={{ width: `${compra.valor / 69885 * 100}%`, background: ["#34c759", "#5ac8fa", "#af52de", "#ff9f0a", "#ff375f", "#8e8e93"][i] }} /></i></div>)}</div></Bloco></>
}
function Metrica({ nome, valor }: { nome: string; valor: string }) { return <div className={estilos.metrica}><small>{nome}</small><strong>{valor}</strong></div> }
function Bloco({ titulo, children }: { titulo: string; children: React.ReactNode }) { return <section className={`${inicio.bloco} ${estilos.bloco}`}><h3>{titulo}</h3>{children}</section> }
function Linhas({ linhas }: { linhas: { nome: string; nota?: string; valor?: number; texto?: string }[] }) { return <ul className={estilos.lista}>{linhas.map((linha) => <li key={linha.nome}><span><strong>{linha.nome}</strong>{linha.nota && <small>{linha.nota}</small>}</span><b>{linha.valor !== undefined ? formatarMoeda(linha.valor) : linha.texto}</b></li>)}</ul> }
export function CabecalhoPrevia({ titulo, modoMei }: { titulo: string; modoMei: boolean }) { return <header className={estilos.cabecalhoTela}><div><h2>{titulo}</h2><span>{modoMei ? "Loja de exemplo" : "Outubro de 2026 · dados fictícios"}</span></div><div className={estilos.ferramentas} aria-hidden><Search size={16} /><Plus size={18} /><Bell size={16} /><span>N</span></div></header> }
export const ICONES_TELA = { inicio: Landmark, cartoes: CreditCard, analise: ArrowUpRight, milhas: Plane, balcao: ShoppingBag, estoque: Package, fiado: ReceiptText, caixa: Banknote }
