"use client"
import { MarcaPersonalizada } from "@/components/identidades-visuais"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useEffect, useState } from "react"
import { CreditCard, Pencil, Plus, Trash2, Upload } from "lucide-react"
import { formatarMoeda, paraCentavos, formatarDecimal } from "@/lib/dinheiro"
import { rotuloCompetencia } from "@/lib/datas"
import { mesesDoCartao,resumoDoMes,type DadosCartao,type CompraCartao,type CompraParcelada } from "@/lib/cartoes"
import { enviar } from "@/lib/cliente"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { SelectNative } from "@/components/ui/select-native"
import { Cartao,Vazio } from "@/components/ui/painel"
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs"
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog"
import { Importador } from "@/components/importador"
import { CompraCartaoForm } from "@/components/compra-cartao-form"
import { IdentidadeBanco } from "@/components/banco-perfil"
import { corDoBanco } from "@/lib/bancos-perfil"
import { AjudaCartao } from "@/components/ajuda-cartao"

export function CentralCartoes({cartoes,categorias,mesAtual}:{cartoes:DadosCartao[];categorias:{id:string;nome:string}[];mesAtual:string}) {
  const router=useRouter();const [id,setId]=useState(cartoes[0]?.id??"");const [mes,setMes]=useState(mesAtual)
  const [categoria,setCategoria]=useState("");const [busca,setBusca]=useState("");const [aba,setAba]=useState("compras")
  const [form,setForm]=useState<{compra?:CompraCartao;parcelamento?:CompraParcelada}|null>(null)
  const [excluir,setExcluir]=useState<{id:string;nome:string;tipo:"transacoes"|"parcelamentos"}|null>(null)
  const [erro,setErro]=useState("");const [ocupado,setOcupado]=useState(false);const [orcamento,setOrcamento]=useState("")
  useEffect(()=>{if(new URLSearchParams(window.location.search).get("aba")==="parcelas")setAba("parcelas")},[])
  const cartao=cartoes.find(c=>c.id===id)??cartoes[0]
  if(!cartao)return <Cartao><Vazio titulo="Adicione seu primeiro cartão" texto="Faturas, compras e parcelas ficam aqui." acao={<Button asChild><Link href="/configuracoes">Cadastrar cartão</Link></Button>}/></Cartao>
  const resumo=resumoDoMes(cartao,mes);const meses=mesesDoCartao(cartao,mesAtual)
  const barras=meses.map(m=>({mes:m,...resumoDoMes(cartao,m)}));const maximo=Math.max(1,...barras.map(b=>Math.max(b.gastos,b.previsto)))
  const compras=resumo.compras.filter(c=>(!categoria||(c.categoriaId??"sem")===categoria)&&c.descricao.toLocaleLowerCase("pt-BR").includes(busca.toLocaleLowerCase("pt-BR")))
  const planejado=cartao.orcamentoMensalCentavos??0
  async function remover(){if(!excluir)return;setOcupado(true);setErro("");try{await enviar(`/api/${excluir.tipo}/${excluir.id}`,{},"DELETE");setExcluir(null);router.refresh()}catch(e){setErro(e instanceof Error?e.message:"Não foi possível excluir.")}finally{setOcupado(false)}}
  async function salvarOrcamento(){setOcupado(true);setErro("");try{await enviar(`/api/cartoes/${cartao.id}/orcamento`,{valorCentavos:paraCentavos(orcamento)},"PUT");router.refresh()}catch(e){setErro(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setOcupado(false)}}
  return <div className="space-y-5">
    <div className="flex gap-3 overflow-x-auto pb-2" aria-label="Escolher cartão">{cartoes.map(c=><button key={c.id} onClick={()=>{setId(c.id);setCategoria("");setOrcamento("")}} aria-pressed={c.id===cartao.id} className={"min-h-14 shrink-0 rounded-2xl border px-4 py-3 text-left "+(c.id===cartao.id?"border-acao bg-acao/10":"border-pauta bg-papel-2")}><span className="block text-sm font-semibold">{c.nome}</span><span className="text-xs text-muted-fg">{c.instituicao??"Cartão de crédito"}</span></button>)}</div>
    <div className="grid gap-4 lg:grid-cols-[1fr_1.2fr]">
      <section className="rounded-3xl p-6 text-white" style={{background:`linear-gradient(135deg, ${corDoBanco(cartao.instituicao)}, #15201e)`}} aria-label={cartao.nome}>
        <div className="flex justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-white/70">{cartao.instituicao??"Cartão"}</p><h2 className="mt-2 text-lg font-semibold">{cartao.nome}</h2></div><IdentidadeBanco instituicao={cartao.instituicao??""} nome={cartao.nome}/></div>
        <p className="mt-7 text-sm text-white/70">Lançamentos de {rotuloCompetencia(mes,true)}</p><p className="mt-1 whitespace-nowrap text-3xl font-semibold tracking-tight">{formatarMoeda(resumo.gastos)}</p>
        <div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm text-white/80"><span>Fecha {cartao.diaFechamento?`dia ${cartao.diaFechamento}`:"não informado"}</span><span>Vence {cartao.diaVencimento?`dia ${cartao.diaVencimento}`:"não informado"}</span></div>
        <p className="mt-3 text-sm text-white/70">Limite bancário: {cartao.limiteCentavos?formatarMoeda(cartao.limiteCentavos):"não informado"}</p>
      </section>
      <Cartao titulo="Faturas por mês"><label className="block text-sm">Mês<SelectNative value={mes} onChange={e=>{setMes(e.target.value);setCategoria("")}}>{meses.map(m=><option key={m} value={m}>{rotuloCompetencia(m)}</option>)}</SelectNative></label>
        <div className="mt-4 flex h-40 items-end gap-2 overflow-x-auto pb-1 pr-16 lg:pr-0">{barras.map(b=><button key={b.mes} aria-label={`${rotuloCompetencia(b.mes)}: ${formatarMoeda(b.gastos)} registrados, ${formatarMoeda(b.previsto)} previstos em parcelas`} aria-pressed={mes===b.mes} onClick={()=>{setMes(b.mes);setCategoria("")}} className="flex h-full min-w-12 flex-1 flex-col justify-end gap-2"><div className="flex h-28 items-end justify-center gap-1"><span className={"w-4 rounded-t-md "+(mes===b.mes?"bg-acao":"bg-acao/35")} style={{height:`${Math.max(3,b.gastos/maximo*100)}%`}}/><span className="w-3 rounded-t-md bg-amber-400/70" style={{height:`${Math.max(3,b.previsto/maximo*100)}%`}}/></div><span className="text-[11px] text-muted-fg">{rotuloCompetencia(b.mes,true)}</span></button>)}</div>
        <p className="mt-3 text-xs text-muted-fg">Verde: lançamentos. Amarelo: parcelas previstas, que podem já constar nos lançamentos.</p>
      </Cartao>
    </div>
    <div className="flex flex-wrap gap-2"><Button onClick={()=>setForm({})}><Plus className="size-4"/>Nova compra</Button><Button variant="outline" onClick={()=>setAba("importar")}><Upload className="size-4"/>Importar fatura</Button></div>
    <Tabs value={aba} onValueChange={setAba}><TabsList className="max-w-full justify-start overflow-x-auto"><TabsTrigger value="compras">Compras</TabsTrigger><TabsTrigger value="parcelas">Parcelas</TabsTrigger><TabsTrigger value="categorias">Categorias</TabsTrigger><TabsTrigger value="orcamento">Orçamento</TabsTrigger><TabsTrigger value="ajuda">Ajuda</TabsTrigger><TabsTrigger value="importar">Importar</TabsTrigger></TabsList>
    <TabsContent value="compras"><Cartao titulo="Compras do mês"><div className="mb-4 grid gap-3 sm:grid-cols-2"><Input aria-label="Buscar compra" placeholder="Buscar compra" value={busca} onChange={e=>setBusca(e.target.value)}/><SelectNative aria-label="Filtrar categoria" value={categoria} onChange={e=>setCategoria(e.target.value)}><option value="">Todas as categorias</option>{resumo.categorias.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</SelectNative></div><p className="mb-3 text-sm text-muted-fg">{compras.length} lançamentos · {formatarMoeda(compras.filter(c=>c.tipo==="DESPESA").reduce((s,c)=>s+c.valorCentavos,0))} em compras</p>
    <div className="divide-y divide-pauta">{compras.map(c=><div key={c.id} className="flex flex-wrap items-center gap-2 py-3"><MarcaPersonalizada nome={c.descricao}/><div className="min-w-0 flex-1"><p className="font-medium">{c.descricao}</p><p className="text-xs text-muted-fg">{c.data.split("-").reverse().join("/")} · {c.categoria?.nome??"Sem categoria"}</p></div><span className="whitespace-nowrap text-sm font-semibold">{c.tipo==="RECEITA"?"Crédito ":""}{formatarMoeda(c.valorCentavos)}</span><Button variant="ghost" size="icon" aria-label={`Editar ${c.descricao}`} onClick={()=>setForm({compra:c})}><Pencil className="size-4"/></Button><Button variant="ghost" size="icon" aria-label={`Excluir ${c.descricao}`} onClick={()=>setExcluir({id:c.id,nome:c.descricao,tipo:"transacoes"})}><Trash2 className="size-4"/></Button></div>)}</div>{!compras.length&&<Vazio titulo="Nenhuma compra neste filtro"/>}</Cartao></TabsContent>
    <TabsContent value="parcelas"><Cartao titulo="Compras parceladas"><p className="mb-4 text-sm text-muted-fg">{formatarMoeda(resumo.previsto)} previstos em {rotuloCompetencia(mes,true)}.</p>{cartao.parcelamentos.map(p=><div key={p.id} className="mb-3 rounded-2xl border border-pauta bg-papel-2 p-4"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><h3 className="font-semibold">{p.descricao}</h3><p className="text-sm text-muted-fg">{p.parcelasPagas} de {p.parcelasTotal} pagas · {formatarMoeda(p.parcelaCentavos)}/mês</p></div><Button variant="ghost" size="icon" aria-label={`Editar parcelamento ${p.descricao}`} onClick={()=>setForm({parcelamento:p})}><Pencil className="size-4"/></Button><Button variant="ghost" size="icon" aria-label={`Excluir parcelamento ${p.descricao}`} onClick={()=>setExcluir({id:p.id,nome:p.descricao,tipo:"parcelamentos"})}><Trash2 className="size-4"/></Button></div><progress aria-label={`Progresso de ${p.descricao}`} className="mt-3 h-2 w-full accent-emerald-500" value={p.parcelasPagas} max={p.parcelasTotal}/><details className="mt-3 text-sm"><summary className="min-h-11 cursor-pointer py-3">Ver calendário de parcelas</summary>{p.parcelas.map(x=><div key={x.id} className={"flex flex-wrap justify-between gap-2 border-t border-pauta py-2 "+(x.competencia===mes?"font-semibold text-acao":"text-muted-fg")}><span>{x.numero}/{p.parcelasTotal} · {rotuloCompetencia(x.competencia,true)}</span><span>{formatarMoeda(x.valorCentavos)} · {x.paga?"Paga":"Prevista"}</span></div>)}</details></div>)}{!cartao.parcelamentos.length&&<Vazio titulo="Sem compras parceladas" texto="Use Nova compra e informe o número de parcelas."/>}</Cartao></TabsContent>
    <TabsContent value="categorias"><Cartao titulo="Para onde foi"><p className="mb-5 text-sm text-muted-fg">Gastos de {rotuloCompetencia(mes,true)}. Escolha uma categoria para ver as compras.</p><div className="grid items-center gap-6 sm:grid-cols-[180px_1fr]"><div className="relative mx-auto size-44 rounded-full" style={{background:resumo.gastos?`conic-gradient(${resumo.categorias.map((c,i,a)=>{const antes=a.slice(0,i).reduce((s,x)=>s+x.totalCentavos,0)/resumo.gastos*100;return `${["#10b981","#38bdf8","#a78bfa","#fbbf24","#fb7185","#94a3b8"][i%6]} ${antes}% ${antes+c.totalCentavos/resumo.gastos*100}%`}).join(",")})`:"#64748b"}}><div className="absolute inset-7 flex flex-col items-center justify-center rounded-full bg-[var(--papel-solido)]"><strong className="text-base">{formatarMoeda(resumo.gastos)}</strong><span className="text-xs text-muted-fg">em compras</span></div></div><div>{resumo.categorias.map((c,i)=><button key={c.id} onClick={()=>{setCategoria(c.id);setAba("compras")}} className="flex min-h-12 w-full items-center gap-3 border-b border-pauta py-2 text-left text-sm"><span className="size-3 shrink-0 rounded-full" style={{background:["#10b981","#38bdf8","#a78bfa","#fbbf24","#fb7185","#94a3b8"][i%6]}}/><span className="flex-1">{c.nome}</span><strong className="whitespace-nowrap">{formatarMoeda(c.totalCentavos)}</strong></button>)}</div></div></Cartao></TabsContent>
    <TabsContent value="orcamento"><Cartao titulo="Seu orçamento para este cartão"><p className="text-sm text-muted-fg">Escolha quanto pretende gastar por mês. O limite concedido pelo banco é separado.</p><div className="my-5 grid gap-3 sm:grid-cols-3">{[["Planejado",planejado],["Compras no mês",resumo.gastos],["Disponível no plano",planejado-resumo.gastos]].map(([titulo,valor])=><div key={String(titulo)} className="rounded-2xl border border-pauta bg-papel-2 p-4"><p className="text-xs text-muted-fg">{titulo}</p><strong className="mt-2 block whitespace-nowrap text-xl">{formatarMoeda(Number(valor))}</strong></div>)}</div><div className="flex flex-wrap items-end gap-3"><label className="text-sm">Orçamento mensal (R$)<Input inputMode="decimal" value={orcamento} placeholder={formatarDecimal(planejado / 100, 2)} onChange={e=>setOrcamento(e.target.value)}/></label><Button disabled={ocupado||!orcamento} onClick={()=>void salvarOrcamento()}>Salvar orçamento</Button></div>{erro&&<p role="alert" className="mt-3 text-negativo">{erro}</p>}</Cartao></TabsContent>
    <TabsContent value="ajuda"><AjudaCartao cartao={cartao} mes={mes}/></TabsContent>
    <TabsContent value="importar"><Importador key={cartao.id} contaInicial={cartao.id} aoConcluir={()=>router.refresh()}/></TabsContent>
    </Tabs>
    {form&&<CompraCartaoForm contaId={cartao.id} categorias={categorias} {...form} fechar={()=>setForm(null)} salvou={()=>router.refresh()}/>}
    <Dialog open={Boolean(excluir)} onOpenChange={a=>{if(!a&&!ocupado)setExcluir(null)}}><DialogContent><DialogHeader><DialogTitle>Excluir {excluir?.tipo==="parcelamentos"?"parcelamento":"compra"}?</DialogTitle><DialogDescription>{excluir?.nome}. Este registro será removido dos cálculos.</DialogDescription></DialogHeader>{erro&&<p role="alert" className="text-negativo">{erro}</p>}<div className="flex justify-end gap-2"><Button variant="outline" disabled={ocupado} onClick={()=>setExcluir(null)}>Cancelar</Button><Button variant="destructive" disabled={ocupado} onClick={()=>void remover()}>{ocupado?"Excluindo…":"Excluir"}</Button></div></DialogContent></Dialog>
  </div>
}
