"use client"
import {createContext,useContext,useEffect,useState} from "react"
import {buscar,enviar} from "@/lib/cliente"
import {Button} from "@/components/ui/button"
import {Input} from "@/components/ui/input"
import {Cartao} from "@/components/ui/painel"
interface Identidade{id:string;nome:string;logoUrl:string|null;emoji:string|null}
const Contexto=createContext<{lista:Identidade[];recarregar:()=>void}>({lista:[],recarregar:()=>{}})
export function IdentidadesProvider({children}:{children:React.ReactNode}){const [lista,setLista]=useState<Identidade[]>([]);function recarregar(){buscar<Identidade[]>("/api/identidades").then(setLista).catch(()=>{})}useEffect(recarregar,[]);return <Contexto.Provider value={{lista,recarregar}}>{children}</Contexto.Provider>}
const normalizar=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()
export function useIdentidadeVisual(nome:string){const {lista}=useContext(Contexto);return [...lista].sort((a,b)=>b.nome.length-a.nome.length).find(x=>normalizar(nome).includes(normalizar(x.nome)))}
export function MarcaPersonalizada({nome}:{nome:string}){const {lista}=useContext(Contexto);const encontrada=[...lista].sort((a,b)=>b.nome.length-a.nome.length).find(x=>normalizar(nome).includes(normalizar(x.nome)));if(!encontrada)return null;return encontrada.logoUrl?<img src={encontrada.logoUrl} alt={encontrada.nome} className="size-9 shrink-0 rounded-xl object-contain"/>:<span aria-label={encontrada.nome} className="text-2xl">{encontrada.emoji??encontrada.nome.slice(0,2).toUpperCase()}</span>}
export function EditorIdentidades(){const {lista,recarregar}=useContext(Contexto);const [nome,setNome]=useState("");const [emoji,setEmoji]=useState("");const [foto,setFoto]=useState<string|null>(null);const [erro,setErro]=useState("");const [ocupado,setOcupado]=useState(false)
 async function salvar(e:React.FormEvent){e.preventDefault();setOcupado(true);setErro("");try{await enviar("/api/identidades",{nome,emoji,logoUrl:foto},"PUT");recarregar();setNome("");setEmoji("");setFoto(null)}catch(e){setErro(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setOcupado(false)}}
 async function ler(f?:File){if(!f)return;if(!["image/png","image/jpeg","image/webp"].includes(f.type)||f.size>500*1024){setErro("Use PNG, JPG ou WebP de até 500 KB.");return}const leitor=new FileReader();leitor.onload=()=>setFoto(String(leitor.result));leitor.readAsDataURL(f)}
 return <Cartao titulo="Logos e estabelecimentos"><p className="mb-4 text-sm text-muted-fg">Associe um logo ou emoji a um nome. Ex.: Uber, Posto Ipiranga ou seu supermercado.</p><form onSubmit={salvar} className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Nome encontrado na compra<Input required maxLength={80} value={nome} onChange={e=>setNome(e.target.value)}/></label><label className="text-sm">Emoji<Input maxLength={24} value={emoji} onChange={e=>setEmoji(e.target.value)} placeholder="🚕"/></label><label className="text-sm">Logo (até 500 KB)<Input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void ler(e.target.files?.[0])}/></label><div className="flex items-end gap-2">{foto&&<img src={foto} alt="Prévia" className="size-11 object-contain"/>}<Button type="submit" disabled={ocupado}>Salvar identidade</Button></div></form>{erro&&<p role="alert" className="mt-3 text-negativo">{erro}</p>}<div className="mt-4 divide-y divide-pauta">{lista.map(x=><div key={x.id} className="flex items-center gap-3 py-2"><MarcaPersonalizada nome={x.nome}/><span className="flex-1">{x.nome}</span><Button variant="ghost" onClick={()=>{setNome(x.nome);setEmoji(x.emoji??"");setFoto(x.logoUrl)}}>Editar</Button><Button variant="ghost" onClick={async()=>{try{await enviar("/api/identidades",{id:x.id},"DELETE");recarregar()}catch{setErro("Não foi possível remover.")}}}>Remover</Button></div>)}</div></Cartao>
}
