import { pathToFileURL } from "node:url"
import { mkdir } from "node:fs/promises"
const modulo = process.env.TINO_PLAYWRIGHT_MODULE
const { chromium } = await import(modulo ? pathToFileURL(modulo).href : "playwright")
await mkdir(".design-reference", {recursive:true})
import assert from "node:assert/strict"
const browser=await chromium.launch({channel:process.env.TINO_BROWSER_CHANNEL || (process.platform==="win32" ? "msedge" : undefined),headless:true})
const context=await browser.newContext({viewport:{width:390,height:844}})
const page=await context.newPage()
const base="http://127.0.0.1:3000"
const prefix="Teste UI "+Date.now()
const ids=[]
const money=n=>(n/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})
try {
 assert.equal((await context.request.post(base+"/api/auth/login",{data:{email:"demo@tino.local",senha:"demo12345"}})).status(),200)
 await page.goto(base+"/transacoes",{waitUntil:"networkidle"})
 await page.getByLabel("Buscar",{exact:true}).fill(prefix)
 await page.getByText("0 lançamento(s) carregado(s)",{exact:true}).waitFor()
 await page.locator(".app-bottom-add").getByRole("button",{name:"Adicionar",exact:true}).click()
 await page.getByRole("button",{name:/Registrar gasto/}).click()
 const form=page.getByRole("dialog")
 await form.getByLabel("Conta",{exact:true}).waitFor()
 await page.waitForFunction(()=>!document.querySelector('[role="dialog"] select')?.disabled)
 await form.getByLabel("Descrição",{exact:true}).fill(prefix+" manual")
 await form.getByLabel("Valor (R$)",{exact:true}).fill("1.234,56")
 await form.getByRole("button",{name:"Salvar",exact:true}).click()
 await form.waitFor({state:"hidden"})
 await page.getByRole("button",{name:prefix+" manual",exact:true}).waitFor()
 let data=await (await context.request.get(base+"/api/transacoes?busca="+encodeURIComponent(prefix))).json()
 ids.push(...data.transacoes.map(t=>t.id))
 assert.equal(data.totais.despesasCentavos,123456)
 assert((await page.locator("dd").allTextContents()).some(t=>t.includes("1.234,56")))
 console.log("create via bottom FAB updates list and totals: OK")
 await page.getByRole("button",{name:money(123456),exact:true}).click()
 const editing=page.locator('li input[inputmode="decimal"]')
 await editing.fill("44,50");await editing.press("Enter")
 await page.getByRole("button",{name:money(4450),exact:true}).waitFor()
 await page.waitForFunction(()=>[...document.querySelectorAll("dd")].some(el=>el.textContent.includes("44,50")))
 console.log("edit updates totals: OK")
 const accounts=await (await context.request.get(base+"/api/contas")).json()
 const now=new Date();const date=now.getFullYear()+"-"+String(now.getMonth()+1).padStart(2,"0")+"-"+String(now.getDate()).padStart(2,"0")
 for(let i=0;i<26;i++) {
  const result=await context.request.post(base+"/api/transacoes",{data:{contaId:accounts[0].id,tipo:"DESPESA",descricao:prefix+" pagina "+i,valorCentavos:100,data:date}})
  assert(result.ok())
  ids.push((await result.json()).id)
 }
 await page.reload({waitUntil:"networkidle"})
 await page.getByLabel("Buscar",{exact:true}).fill(prefix)
 await page.getByText("25 lançamento(s) carregado(s)",{exact:true}).waitFor()
 await page.getByRole("button",{name:"Carregar mais",exact:true}).click()
 await page.getByText("27 lançamento(s) carregado(s)",{exact:true}).waitFor()
 assert((await page.locator("dd").allTextContents()).some(t=>t.includes("70,50")))
 console.log("cursor pagination + full-filter totals: OK")
 await page.getByRole("button",{name:"Mais recursos",exact:true}).filter({visible:true}).click()
 const dialog=page.getByRole("dialog")
 const box=await dialog.boundingBox();assert(box.x>=0 && box.y>=0 && box.y+box.height<=845)
 await page.keyboard.press("Tab")
 assert(await page.evaluate(()=>document.querySelector('[role="dialog"]').contains(document.activeElement)))
 await page.keyboard.press("Escape")
 assert(await page.getByRole("button",{name:"Mais recursos",exact:true}).filter({visible:true}).evaluate(el=>el===document.activeElement))
 console.log("dialog bounded, focus trapped and restored: OK")
 await page.getByRole("button",{name:"Falar com o Tino",exact:true}).click()
 assert(await page.getByRole("button",{name:"Enviar pergunta",exact:true}).isVisible())
 await page.keyboard.press("Escape")
 console.log("chat dialog opens and closes: OK")
} finally {
 for(const id of ids) if(id) await context.request.delete(base+"/api/transacoes/"+id)
 await browser.close()
 console.log("temporary fixtures removed:",ids.length)
}